server:
  port: 8081
spring:
  redis:
#    host: 127.0.0.1
    host: 192.168.1.11
    password: 123456
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 8
        min-idle: 0
